version: "3.8"

services:
  postgresqldb:
    image: postgres:15-alpine
    container_name: postgresqldb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/data/db
    environment:
      POSTGRES_PASSWORD: mhaddaou

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - postgresqldb
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command: npm start
    
volumes:
  postgresql-data:
  app:

networks:
  default:
    name: my_network
