import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/main/Navbar";
import { Providers } from "./Providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` overflow-x-hidden  bg-background`}>
        <Providers>
          <NavBar />
          <Toaster position="top-right" richColors />
          {children}
        </Providers>
      </body>
    </html>
  );
}
